#-------------------------------
# General Site Settings

title: Vệ Giang's Blog
description: Ghé thăm blog cá nhân Vegiang.com để có thêm nhiều thông tin, trải nghiệm sống chân thật nhất từ kinh nghiệm sống, làm việc, du lịch, giải trí
logo: '/images/logo.jpg'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vegiang.com/" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# Author Settings
author:
  name: Trần Hương Vệ Giang
  image: '/images/15.jpg'
  avatar: '/images/01.jpg'
  # job: Designer
  bio: Chào bạn! Mình là một Content Writer và đây là Blog của mình


#-------------------------------
# Contact links
# Example of adding a new link to the header - {icon: "ion-logo-github", link: "https://github.com"}
# Other icons can be found at https://ionicons.com
contact:
- {icon: "ion-logo-facebook", link: "https://www.facebook.com/vegiangblog"}
- {icon: "ion-logo-instagram", link: "https://www.instagram.com/ve_giang/"}
- {icon: "ion-logo-youtube", link: "https://www.youtube.com/channel/UCLkh6Fhs_qrsBe0n61e_DNQ"}


#-------------------------------
# Slider Section
slider: true # NOTE - By default, the slider is set to display featured posts. To add featured post to the slider, add the field, featured: true in the YAML front matter block. If you do not want to use the slider, leave the slider field empty.

# For example:
# ---
# layout: post
# featured: true
# ---

#-------------------------------
# Comment Section (Disqus)
# disqus-identifier: vegiang # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Gallery Section (Sidebar)
gallery:
  name: Gallery
  images:
    - alt: 'Hình Giang Chụp 1'
      url: '/images/hinh-giang-chup1.jpg'
    - alt: 'Hình Giang Chup 2'
      url: '/images/hinh-giang-chup2.jpg'
    - alt: 'Hình Giang Chup 3'
      url: '/images/hinh-giang-chup3.jpg'
    - alt: 'Hình Giang Chup 4'
      url: '/images/hinh-giang-chup4.jpg'
    - alt: 'Hình Giang Chup 5'
      url: '/images/hinh-giang-chup5.jpg'
    - alt: 'Hình Giang Chup 6'
      url: '/images/hinh-giang-chup6.jpg'
    - alt: 'Hình Giang Chup 7'
      url: '/images/hinh-giang-chup7.jpg'
    - alt: 'Hình Giang Chup 8'
      url: '/images/hinh-giang-chup8.JPG'
    - alt: 'Hình Giang Chup 9'
      url: '/images/hinh-giang-chup-9.JPG'

#-------------------------------
# Google Analytics
google-analytics: UA-96364919-2 # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
# mailchimp: true # To enable the mailchimp form, use the value true. To turn off use the value false.
# mailchimp-identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 8
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed
